// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OVXqnfDN-40ETRI7VmSnOxKcI5FzmMw',
    appId: '1:664199155105:android:375d75def098d6ff370fe0',
    messagingSenderId: '664199155105',
    projectId: 'amar-pharmacy-1',
    storageBucket: 'amar-pharmacy-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYuL7GjkJF_nzch8cQljuJCLUHJwQEmtk',
    appId: '1:664199155105:ios:0ca09fb84bfa3d71370fe0',
    messagingSenderId: '664199155105',
    projectId: 'amar-pharmacy-1',
    storageBucket: 'amar-pharmacy-1.appspot.com',
    androidClientId: '664199155105-ve0cmvessn6dj51aj4nm6qtd5qae9kte.apps.googleusercontent.com',
    iosClientId: '664199155105-kdh92j5a92jlcba4kcha7uhfb22nghcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.amarPharmacy',
  );
}
